### PR TITLE
Abstract Serial off to Service, version lock dependencies, unit tests

### PR DESCRIPTION
**Pull request by CaptainGlac1er**

### CODE REVIEW

**Comment by samcervantes** [comment]
For some reason I wasn't able to get this to work on my pi. After checking out the branch, I installed python 3.8 (my pi image shipped with 3.7), ran `pipenv install`, fired up a `pipenv shell`, and  when I tried to start the server I got an error: `NameError: name 'serial_connection' is not defined` referring to line 35. Line 35 is the following: `line = serial_connection.request("getStats\n")` My arduino is connected to the serial port `/dev/ttyACM0` and it seems to have worked fine before the code checkout.

**Comment by CaptainGlac1er** [comment]
@samcervantes how are you executing the python file?

**Comment by samcervantes** [comment]
I've tried running it with the start.sh script

**Comment by CaptainGlac1er** [comment]
@samcervantes could you try again with the latest version of this branch? (I haven't set up my pi yet)

**Comment by CaptainGlac1er** [comment]
Realized I missed updating the start,sh

**Comment by CaptainGlac1er** [comment]
@samcervantes added gunicorn as a dependency so everything can run within the pipenv

**Pull request merged**
